# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    tags:
      - 'v*'
jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Test Product Review Service
      run: mvn clean test -f ./product_review/pom.xml
    - name: Test Product API
      run: mvn clean test -f ./product_service/pom.xml

  build:

    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build Product Review Service
      run: mvn clean package -f ./product_review/pom.xml
    - name: Build Product API
      run: mvn clean package -f ./product_service/pom.xml

  publish-on-docker:

    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            name/app
          tags: |
            type=semver,pattern={{version}}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Product Review
        uses: docker/build-push-action@v3
        with:
          context: ./product_review
          push: true
          repository: kouroshtaf/product_review
          tags: ${{ steps.meta.outputs.tags }}
      
      - name: Build and push Product API
        uses: docker/build-push-action@v3
        with:
          context: ./product_service
          push: true
          repository: kouroshtaf/product_service
          tags: ${{ steps.meta.outputs.tags }}